config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root to: 'jobs#index'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :vacancies, dependent: :destroy
  default_scope { order('id DESC') }
  after_create :notification, if: :exists_new_vacancies

  def exists_new_vacancies
    new_one = Job.first.vacancies.pluck(:plan_id, :date)
    old_one = Job.second.vacancies.pluck(:plan_id, :date)
    (new_one - old_one).present?
  end

  def notification
    NotificationMailer.push(self).deliver
  end
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  belongs_to :job
  belongs_to :plan

  default_scope { order('id ASC') }

  def to_s
    "#{date.strftime('%Y/%m/%d')} (#{price.to_s(:delimited)}円)"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all.limit(50)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/index.html.erb
<div class="container">
  <section class="content-header">
  </section>
  <section class="content">
    <div class="box">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="col-lg-2">チェック日付</th>
            <% Plan.all.each do |plan| %>
            <th><%= plan.name %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @jobs.each do |job| %>
          <tr>
            <td><%= job.created_at.strftime('%Y/%m/%d %H:%M') %></td>
            <% Plan.all.each do |plan| %>
            <td>
              <% job.vacancies.where(plan: plan).each.with_index do |vacancy, index| %>
                <%= link_to vacancy.to_s, "#{plan.url}&dt=#{vacancy.date.strftime('%Y%m%d')}", target: '_blank' %>
                <br>
              <% end %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </section>
</div>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ミラコスタ チェッカー</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  </head>
  <body class="hold-transition skin-blue layout-top-nav">
    <div class="wrapper">
      <%= render 'shared/header' %>
      <div class="content-wrapper">
        <%= yield %>
      </div>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="main-footer">
  <div class="container">
    <div class="pull-right hidden-xs">
      <b>Version</b> 0.0.1
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="main-header">
  <nav class="navbar navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <a href="/" class="navbar-brand">ミラコスタ チェッカー</a>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
          <i class="fa fa-bars"></i>
        </button>
      </div>
    </div>
  </nav>
</header>